CREATE TABLE Type (
	Id INTEGER IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Ingredient (
	Id INTEGER IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Description (
	Id INTEGER IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Method (
	Id INTEGER IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Recipe (
	Id INTEGER IDENTITY,
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Dish (
	Id INTEGER IDENTITY,
	TypeId INTEGER FOREIGN KEY REFERENCES Type(Id),
	IngredientId INTEGER FOREIGN KEY REFERENCES Ingredient(Id),
	DescriptionId INTEGER FOREIGN KEY REFERENCES Description(Id),
	Name VARCHAR(50) NOT NULL,
	Price INTEGER NOT NULL,
	Speed INTEGER NOT NULL,
	Difficulty INTEGER
)

CREATE TABLE DishToMethod(
	DishId INTEGER FOREIGN KEY REFERENCES Dish(Id),
	MethodId INTEGER FOREIGN KEY REFERENCES Method(Id),
	Order INTEGER NOT NULL
)

CREATE TABLE DishToRecipe (
	Id INTEGER UNIQUE FOREIGN KEY REFERENCES Dish(Id),
	RecipeId INTEGER FOREIGN KEY REFERENCES Recipe(Id),
	Page VARCHAR(255)
)

INSERT INTO Type (Name) VALUES ('Main')
INSERT INTO Type (Name) VALUES ('Side')
INSERT INTO Type (Name) VALUES ('Vegetable')
