INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Parmesan Tilapia',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Sausages',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Grilled Beef and Blue Cheese Sandwiches',3,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Gorgonzola Orange Chicken Tenders',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Waffles and fruit',1,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Garlic Chicken',2,1,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Slow Cooker Pork tenderloin',3,3,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Sweet and Spicy Stir Fry',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Grilled cheese sandwiches',1,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Blue Cheese Burgers',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Black bean and corn quesadillas',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Sirlion and chicken fondue',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Lemon Chicken Primavera',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Rigatoni with Sausage and Peas',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Hubby''s Favorite Crepes',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Mango Chutney Chicken Curry',3,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Glazed Roast Chicken',3,3,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Cream Cheese Chicken Squares',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Mediterranean Baked Chicken with Lemon',2,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Brie Herb Fondue',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Balsamic Chicken',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Chili Sauce Chicken',2,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Grilled Basil Chicken',2,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Hearty Pork Chops',2,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Apple-Marinated Chicken &Vegetables',2,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('On the Go Breakfast Muffins',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Sausage Gravy and Biscuits',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Asparagus and Corn Quiche',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Tangy BBQ Beef Sandwiches',3,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Chicken Taco Burgers',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Bacon-Blue Cheese Stuffed Burgers',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Savory Garlic Beef & Broccoli Turnovers',3,2,3, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Asparagus Tart',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Stuffing Dumpling Soup',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Simple Tomato Soup',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Teriyaki Chicken Stew',3,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Chipotle Chili',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Mexican Chicken Chili',2,3,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Spring Salmon Chowder',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Turkey Sweet Potato Soup',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Turkey Gnocchi Soup',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Chunky Chipotle Pork Chili',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Stephanie''s Slow Cooker Stew',3,3,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Best Ever Chicken Fajita Chowder',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Minsetrone',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Pasta alla Romana',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Braised Chicken',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Beef stew with wine',3,3,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Cranberry Bean Chili',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Aloo Chana',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Pressure Cooker Ribs',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Indian Veggie Pullow',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Chipotle Burritos',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('French Toast',1,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Creamy Pork Chop Casserole',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Hot Pot Fondue',3,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Quiche',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Tacos',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Broccoli Cous Cous',1,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Grilled Herb Potatoes',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Oven roasted potatoes',1,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Sweet potato fries',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Rice Mix',1,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Rice Pilaf',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Wild rice',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Quinoa',3,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Creamed Peas',1,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Roasted Asparagus',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Glazed carrots',1,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Thymed Zucchini Saute',2,2,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Salad kit',2,1,1, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Wedge salad',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Blue cheese sauce',2,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Seasoned Green Beans',1,2,2, '', '');
INSERT INTO Recipe (name, price, speed, difficulty, directions, location) VALUES('Beer cheese sauce',2,2,1, '', '');